# Generated by Django 2.2.6 on 2020-10-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='calificaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(blank=True, db_column='matricula', max_length=80, null=True)),
                ('claveMateria', models.CharField(blank=True, db_column='claveMateria', max_length=80, null=True)),
                ('calif', models.CharField(blank=True, db_column='calif', max_length=10, null=True)),
                ('estrategia', models.CharField(blank=True, db_column='estrategia', max_length=300, null=True)),
            ],
            options={
                'db_table': 'calificaiones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='docentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claveDocente', models.IntegerField(blank=True, db_column='claveDocente', null=True)),
                ('nombre', models.CharField(blank=True, db_column='nombre', max_length=80, null=True)),
                ('apellidoP', models.CharField(blank=True, db_column='apellidoP', max_length=80, null=True)),
                ('apellidoM', models.CharField(blank=True, db_column='apellidoM', max_length=80, null=True)),
                ('email', models.CharField(blank=True, db_column='email', max_length=80, null=True)),
                ('curp', models.CharField(blank=True, db_column='curp', max_length=80, null=True)),
            ],
            options={
                'db_table': 'docentes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='grupos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claveGrupo', models.CharField(blank=True, db_column='claveGrupo', max_length=80, null=True)),
                ('claveDocente', models.CharField(blank=True, db_column='claveDocente', max_length=80, null=True)),
                ('claveMateria', models.CharField(blank=True, db_column='claveMateria', max_length=80, null=True)),
                ('grado', models.IntegerField(blank=True, db_column='grado', null=True)),
                ('grupo', models.CharField(blank=True, db_column='grupo', max_length=1, null=True)),
            ],
            options={
                'db_table': 'grupo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='materias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claveMateria', models.CharField(blank=True, db_column='claveMateria', max_length=80, null=True)),
                ('nombreMateria', models.CharField(blank=True, db_column='nombreMateria', max_length=80, null=True)),
            ],
            options={
                'db_table': 'materias',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='alumnos',
            options={'managed': False},
        ),
    ]
