# Generated by Django 2.2.6 on 2020-10-08 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagement', '0002_auto_20201008_0005'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alumnos',
            table='alumnos',
        ),
    ]
