# Generated by Django 2.2.6 on 2020-10-09 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagement', '0003_auto_20201008_0007'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='calificaciones',
            table='calificaciones',
        ),
    ]
