# Generated by Django 2.2.6 on 2020-11-04 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagement', '0004_auto_20201008_2246'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='grupos',
            table='groups',
        ),
    ]
