# Generated by Django 2.2.6 on 2020-11-04 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagement', '0005_auto_20201103_2157'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='calificaciones',
            table='calificacion',
        ),
    ]
