# Generated by Django 2.2.6 on 2020-11-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagement', '0006_auto_20201103_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='calificacion',
            fields=[
                ('incremento', models.AutoField(primary_key=True, serialize=False)),
                ('calif', models.CharField(blank=True, db_column='calif', max_length=3, null=True)),
                ('estrategia', models.CharField(blank=True, db_column='estrategia', max_length=300, null=True)),
            ],
            options={
                'db_table': 'calificacion',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='calificaciones',
        ),
    ]
